export default {
  "PROFILE_VERSION": "11",
  "AddressDetails.BillingAddress.AddressLine1": "Klosterwall 4",
  "AddressDetails.BillingAddress.AddressLine2": "2A",
  "AddressDetails.BillingAddress.AdministrativeArea": "Hamburg",
  "AddressDetails.BillingAddress.CompanyName": "Billing Company",
  "AddressDetails.BillingAddress.Country": "Germany",
  "AddressDetails.BillingAddress.PostalCode": "06925",
  "AddressDetails.BillingAddress.StreetNumber": "4",
  "AddressDetails.BillingAddress.StreetName": "Klosterwall",
  "AddressDetails.BillingAddress.Suburb": "Hamburg",
  "AddressDetails.HomeAddress.AddressLine1": "Kieler Strasse 31",
  "AddressDetails.HomeAddress.AddressLine2": "2A",
  "AddressDetails.HomeAddress.AdministrativeArea": "Neumunster",
  "AddressDetails.HomeAddress.CompanyName": "Home Company",
  "AddressDetails.HomeAddress.Country": "Germany",
  "AddressDetails.HomeAddress.PostalCode": "82282",
  "AddressDetails.HomeAddress.StreetNumber": "31A",
  "AddressDetails.HomeAddress.StreetName": "Kieler Strasse",
  "AddressDetails.HomeAddress.Suburb": "Neumunster",
  "AddressDetails.PostalAddress.AddressLine1": "Rudolstaedter Strasse 41",
  "AddressDetails.PostalAddress.AddressLine2": "2",
  "AddressDetails.PostalAddress.AdministrativeArea": "Orlamünde",
  "AddressDetails.PostalAddress.CompanyName": "Postal Company",
  "AddressDetails.PostalAddress.Country": "Germany",
  "AddressDetails.PostalAddress.PostalCode": "63818",
  "AddressDetails.PostalAddress.StreetNumber": "41A",
  "AddressDetails.PostalAddress.StreetName": "Rudolstaedter Strasse",
  "AddressDetails.PostalAddress.Suburb": "Orlamünde",
  "AddressDetails.WorkAddress.AddressLine1": "Klosterwall 4",
  "AddressDetails.WorkAddress.CompanyName": "Work Company",
  "AddressDetails.WorkAddress.Country": "Germany",
  "AddressDetails.WorkAddress.PostalCode": "06925",
  "AddressDetails.WorkAddress.Suburb": "Hamburg",
  "ContactDetails.CellPhones.CellPhone.CountryCode": "49",
  "ContactDetails.CellPhones.CellPhone.Number": "301234567",
  "ContactDetails.Emails.Email.Address": "test@gmail.com",
  "ContactDetails.LandlinePhones.LandlinePhone": "5439136",
  "ContactDetails.LandlinePhones.LandlinePhone.AreaCode": "03",
  "ContactDetails.LandlinePhones.LandlinePhone.CountryCode": "49",
  "ContactDetails.LandlinePhones.LandlinePhone.Extension": "12",
  "ContactDetails.LandlinePhones.LandlinePhone.Number": "03",
  "CreditCards.CreditCard.CCV": "123",
  "CreditCards.CreditCard.Expiry": "09-2021",
  "CreditCards.CreditCard.Expiry.Month": "09",
  "CreditCards.CreditCard.Expiry.Year": "2021",
  "CreditCards.CreditCard.NameOnCard": "John Wick",
  "CreditCards.CreditCard.Number": "4242424242424242",
  "CreditCards.CreditCard.Type": "VISA",
  "IdentificationDetails.Licenses.License.ExpiryDate.Day": "05",
  "IdentificationDetails.Licenses.License.ExpiryDate.Month": "06",
  "IdentificationDetails.Licenses.License.ExpiryDate.Year": "2019",
  "IdentificationDetails.Licenses.License.IssueCity": "city",
  "IdentificationDetails.Licenses.License.IssueCountry": "country",
  "IdentificationDetails.Licenses.License.IssueDate.Day": "01",
  "IdentificationDetails.Licenses.License.IssueDate.Month": "11",
  "IdentificationDetails.Licenses.License.IssueDate.Year": "2017",
  "IdentificationDetails.Licenses.License.IssueState": "state",
  "IdentificationDetails.Licenses.License.IssuerName": "issuer name",
  "IdentificationDetails.Licenses.License.Name": "name",
  "IdentificationDetails.Licenses.License.Number": "123456789",
  "IdentificationDetails.Licenses.License.Restrictions": "Restrictions",
  "IdentificationDetails.Licenses.License.Status": "License Status",
  "IdentificationDetails.Licenses.License.Type": "identificaiton type",
  "IdentificationDetails.Passports.Passport.Authority": "PP Authority",
  "IdentificationDetails.Passports.Passport.CountryOfIssue": "Country of Issue",
  "IdentificationDetails.Passports.Passport.DateOfIssue.Day": "01",
  "IdentificationDetails.Passports.Passport.DateOfIssue.Month": "05",
  "IdentificationDetails.Passports.Passport.DateOfIssue.Year": "2014",
  "IdentificationDetails.Passports.Passport.ExpiryDate.Day": "09",
  "IdentificationDetails.Passports.Passport.ExpiryDate.Month": "08",
  "IdentificationDetails.Passports.Passport.ExpiryDate.Year": "2019",
  "IdentificationDetails.Passports.Passport.Name": "Passport Name",
  "IdentificationDetails.Passports.Passport.Number": "N02547897",
  "Passwords.Password.Password": "Password01",
  "PersonalDetails.BirthDate": "01-11-1990",
  "PersonalDetails.BirthDate.Day": "01",
  "PersonalDetails.BirthDate.Month": "11",
  "PersonalDetails.BirthDate.Year": "1990",
  "PersonalDetails.CompanyName": "Personal Company",
  "PersonalDetails.FirstName": "John",
  "PersonalDetails.FullName": "John Wick",
  "PersonalDetails.Gender": "Herr",
  "PersonalDetails.Honorific": "Mr.",
  "PersonalDetails.LastName": "Wick",
  "PersonalDetails.MiddleName": "Middle Pop",
  "PersonalDetails.Role": "Chief Scientist",
  "PersonalDetails.SocialSecurityNumber": "5208171258",
  "PersonalDetails.TaxFileNumber": "865414088",
  "Usernames.Username.Username": "myusername"
}