export default {
    "PROFILE_VERSION":"8",
    "Usernames.Username.Username":"myusername",
    "PersonalDetails.Honorific":"Mr.",
    "PersonalDetails.FirstName":"John",
    "PersonalDetails.MiddleName":"Middle Pop",
    "PersonalDetails.LastName":"Wick",
    "Passwords.Password.Password":"password",
    "PersonalDetails.Gender":"Male",
    "PersonalDetails.SocialSecurityNumber":"5208171258",
    "PersonalDetails.TaxFileNumber":"865414088",
    "PersonalDetails.Role":"Chief Scientist",
    "PersonalDetails.CompanyName":"Fillr",
    "ContactDetails.CellPhones.CellPhone.Number":"0400000000",
    "ContactDetails.CellPhones.CellPhone.CountryCode":"61",
    "ContactDetails.LandlinePhones.LandlinePhone.Number":"98551234",
    "ContactDetails.LandlinePhones.LandlinePhone.CountryCode":"1",
    "ContactDetails.LandlinePhones.LandlinePhone.AreaCode":"03",
    "ContactDetails.LandlinePhones.LandlinePhone.Extension":"12",
    "PersonalDetails.BirthDate.Day":"01",
    "PersonalDetails.BirthDate.Month":"11",
    "PersonalDetails.BirthDate.Year":"1990",
    "PersonalDetails.BirthDate":"01-11-1990",
    "ContactDetails.Emails.Email.Address":"jamesws007@gmail.com",
    "CreditCards.CreditCard.NameOnCard":"John Wick",
    "CreditCards.CreditCard.Number":"4242424242424242",
    "CreditCards.CreditCard.Expiry":"09-2021",
    "CreditCards.CreditCard.Type":"VISA",
    "CreditCards.CreditCard.Expiry.Month":"09",
    "CreditCards.CreditCard.Expiry.Year":"2021",
    "CreditCards.CreditCard.CCV":"123",
    "AddressDetails.WorkAddress.AddressLine1":"1/30-32 Smith street",
    "AddressDetails.WorkAddress.AddressLine2":"Postal Line2",
    "AddressDetails.WorkAddress.Suburb":"Walkerville",
    "AddressDetails.WorkAddress.PostalCode":"5081",
    "AddressDetails.WorkAddress.AdministrativeArea":"SA",
    "AddressDetails.WorkAddress.Country":"Australia",
    "AddressDetails.BillingAddress.AddressLine1":"144 Burwood Hwy",
    "AddressDetails.BillingAddress.AddressLine2":"Billing Line 2",
    "AddressDetails.BillingAddress.Suburb":"Burwood",
    "AddressDetails.BillingAddress.PostalCode":"3125",
    "AddressDetails.BillingAddress.AdministrativeArea":"VIC",
    "AddressDetails.BillingAddress.Country":"Australia",
    "AddressDetails.PostalAddress.AddressLine1":"6/176 Murrumbeena Rd",
    "AddressDetails.PostalAddress.AddressLine2":"Address Line 2",
    "AddressDetails.PostalAddress.Suburb":"Murrumbeena",
    "AddressDetails.PostalAddress.PostalCode":"3163",
    "AddressDetails.PostalAddress.AdministrativeArea":"VIC",
    "AddressDetails.PostalAddress.Country":"Australia",
    "IdentificationDetails.Licenses.License.Type":"identificaiton type",
    "IdentificationDetails.Licenses.License.Number":"123456789",
    "IdentificationDetails.Licenses.License.IssuerName":"issuer name",
    "IdentificationDetails.Licenses.License.Name":"name",
    "IdentificationDetails.Licenses.License.IssueCity":"city",
    "IdentificationDetails.Licenses.License.IssueState":"state",
    "IdentificationDetails.Licenses.License.IssueCountry":"country",
    "IdentificationDetails.Licenses.License.IssueDate.Day":"01",
    "IdentificationDetails.Licenses.License.IssueDate.Month":"11",
    "IdentificationDetails.Licenses.License.IssueDate.Year":"2017",
    "IdentificationDetails.Licenses.License.ExpiryDate.Day":"05",
    "IdentificationDetails.Licenses.License.ExpiryDate.Month":"06",
    "IdentificationDetails.Licenses.License.ExpiryDate.Year":"2019",
    "IdentificationDetails.Licenses.License.Status":"License Status",
    "IdentificationDetails.Licenses.License.Restrictions":"Restrictions",
    "IdentificationDetails.Passports.Passport.Number":"N02547897",
    "IdentificationDetails.Passports.Passport.Name":"Passport Name",
    "IdentificationDetails.Passports.Passport.CountryOfIssue":"Country of Issue",
    "IdentificationDetails.Passports.Passport.DateOfIssue.Day":"01",
    "IdentificationDetails.Passports.Passport.DateOfIssue.Month":"05",
    "IdentificationDetails.Passports.Passport.DateOfIssue.Year":"2014",
    "IdentificationDetails.Passports.Passport.ExpiryDate.Day":"09",
    "IdentificationDetails.Passports.Passport.ExpiryDate.Month":"08",
    "IdentificationDetails.Passports.Passport.ExpiryDate.Year":"2019",
    "IdentificationDetails.Passports.Passport.Authority":"PP Authority"
  }
  